name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: anndreloopez012
      - name: Commit generated profile assets
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update 3d contribution calendar"
          file_pattern: profile-3d-contrib/*.svg
